// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gglmfscrnyxvuyvwfxkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbG1mc2Nybnl4dnV5dndmeGt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzAyNzIsImV4cCI6MjA2MDIwNjI3Mn0.3qScP80UckABrqHH10ta378-hVv8N3PK2WwHKzjWpXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);